commented out workflow for sonar and integration test.

diff --git a/.github/workflows/integration_run.yml b/.github/workflows/integration_run.yml
--- a/.github/workflows/integration_run.yml
+++ b/.github/workflows/integration_run.yml
@@ -1,104 +1,104 @@
-name: Run Pebblo Integration Tests
-on:
-  schedule:
-    - cron: '30 2,14 * * *'
+# name: Run Pebblo Integration Tests
+# on:
+#   schedule:
+#     - cron: '30 2,14 * * *'
 
-  workflow_dispatch: # Activate this workflow manually
-env:
-  PYTHON_VERSION: ${{ github.event.inputs.python_version || '3.11.x' }}
-  OPENAI_API_KEY_SECRET: ${{ secrets.OPENAI_API_KEY }}
-  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
-  SLACK_CH: ${{ secrets.SLACK_CH }}
-jobs:
-  Setup_Pebblo_Run_Tests:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v2
+#   workflow_dispatch: # Activate this workflow manually
+# env:
+#   PYTHON_VERSION: ${{ github.event.inputs.python_version || '3.11.x' }}
+#   OPENAI_API_KEY_SECRET: ${{ secrets.OPENAI_API_KEY }}
+#   SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
+#   SLACK_CH: ${{ secrets.SLACK_CH }}
+# jobs:
+#   Setup_Pebblo_Run_Tests:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout Repository
+#         uses: actions/checkout@v2
         
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          ref: 'main'
-          python-version: ${{ env.PYTHON_VERSION }}
+#       - name: Set up Python
+#         uses: actions/setup-python@v4
+#         with:
+#           ref: 'main'
+#           python-version: ${{ env.PYTHON_VERSION }}
 
-      - name: Build Pebblo
-        run: |
-          pip install build
-          python -m build --wheel
-          ls -la dist/
+#       - name: Build Pebblo
+#         run: |
+#           pip install build
+#           python -m build --wheel
+#           ls -la dist/
           
-      - name: Install Pebblo Packages
-        run: |
-            echo 'Install Pebblo Package'
-            pkg_file=$(ls dist | grep .whl)
-            pip3 install dist/$pkg_file --force-reinstall
-            pip3 install --upgrade pip
+#       - name: Install Pebblo Packages
+#         run: |
+#             echo 'Install Pebblo Package'
+#             pkg_file=$(ls dist | grep .whl)
+#             pip3 install dist/$pkg_file --force-reinstall
+#             pip3 install --upgrade pip
             
-      - name: Start Pebblo Server
-        run: |
-            echo 'Running Pebblo server'
-            sleep 10
-            pebblo &
-            sleep 120
+#       - name: Start Pebblo Server
+#         run: |
+#             echo 'Running Pebblo server'
+#             sleep 10
+#             pebblo &
+#             sleep 120
 
-      - name: Verify Pebblo Server
-        run: |
-          cat /tmp/logs/pebblo.log
+#       - name: Verify Pebblo Server
+#         run: |
+#           cat /tmp/logs/pebblo.log
           
-          if grep -q "Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)" /tmp/logs/pebblo.log; then
-            echo "Server started successfully."
-          else
-            echo "Unexpected issue detected at server."
-            exit 1 
-          fi
+#           if grep -q "Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)" /tmp/logs/pebblo.log; then
+#             echo "Server started successfully."
+#           else
+#             echo "Unexpected issue detected at server."
+#             exit 1 
+#           fi
   
-      - name: Install Required Sample Application Dependencies
-        run: |
-            echo 'Install Sample Application dependency'
-            pip3 install --upgrade pip
-            pip3 install -r tests/integration/samples/requirements.txt --force-reinstall
+#       - name: Install Required Sample Application Dependencies
+#         run: |
+#             echo 'Install Sample Application dependency'
+#             pip3 install --upgrade pip
+#             pip3 install -r tests/integration/samples/requirements.txt --force-reinstall
             
-      - name: Run Sample RAG App
-        run: | 
-            export OPENAI_API_KEY=$OPENAI_API_KEY_SECRET
-            echo 'Running pebblo_csvloader Samples'
-            cd tests/integration/samples/pebblo_csv_loader
-            python3 pebblo_csvloader.py 
-            cd ../../
-            sleep 300
+#       - name: Run Sample RAG App
+#         run: | 
+#             export OPENAI_API_KEY=$OPENAI_API_KEY_SECRET
+#             echo 'Running pebblo_csvloader Samples'
+#             cd tests/integration/samples/pebblo_csv_loader
+#             python3 pebblo_csvloader.py 
+#             cd ../../
+#             sleep 300
 
-      - name: Check Pebblo App Run Logs
-        run: |
-          cat /tmp/logs/pebblo.log
+#       - name: Check Pebblo App Run Logs
+#         run: |
+#           cat /tmp/logs/pebblo.log
 
-      - name: Upload Pebblo App Run Logs as Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: Pebblo_Report
-          path: |
-            /tmp/logs/pebblo.log
+#       - name: Upload Pebblo App Run Logs as Artifact
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: Pebblo_Report
+#           path: |
+#             /tmp/logs/pebblo.log
 
-      - name: Check logs for Pebblo Report 
-        run: |
-          if grep -q "INFO - PDF report generated, please check path : /home/runner/.pebblo/" /tmp/logs/pebblo.log; then
-            echo "Report Generated Successfully."
-          else
-            echo "Unexpected issue detected at running sample app."
-            cat /tmp/logs/pebblo.log
-            exit 1 
-          fi 
+#       - name: Check logs for Pebblo Report 
+#         run: |
+#           if grep -q "INFO - PDF report generated, please check path : /home/runner/.pebblo/" /tmp/logs/pebblo.log; then
+#             echo "Report Generated Successfully."
+#           else
+#             echo "Unexpected issue detected at running sample app."
+#             cat /tmp/logs/pebblo.log
+#             exit 1 
+#           fi 
 
-      - name: Upload Pebblo Report File
-        run: |
-           cd /home/runner/.pebblo/Pebblo_Automation_Testing_CSVLoader  
-           curl -F file=@pebblo_report.pdf https://slack.com/api/files.upload -H "Authorization: Bearer $SLACK_TOKEN" -F channels=$SLACK_CH -F "initial_comment=Pebblo Nightly Report"
+#       - name: Upload Pebblo Report File
+#         run: |
+#            cd /home/runner/.pebblo/Pebblo_Automation_Testing_CSVLoader  
+#            curl -F file=@pebblo_report.pdf https://slack.com/api/files.upload -H "Authorization: Bearer $SLACK_TOKEN" -F channels=$SLACK_CH -F "initial_comment=Pebblo Nightly Report"
 
-      - name: Report Status if test case or build failure
-        if: always()
-        uses: ravsamhq/notify-slack-action@master
-        with:
-          status: ${{ job.status }}
-          notify_when: 'failure'
-        env:
-          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_SECRET }}            
+#       - name: Report Status if test case or build failure
+#         if: always()
+#         uses: ravsamhq/notify-slack-action@master
+#         with:
+#           status: ${{ job.status }}
+#           notify_when: 'failure'
+#         env:
+#           SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_SECRET }}            
